[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]

[start]
cmd = "python main.py"